spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agenda_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

# Configuración de JWT
jwt:
  secret: TuSecretoMuyLargoYSeguroQueCambiarásEnProducción
  expirationMs: 86400000  # 24 horas en milisegundos
